name: Run Example test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
  QASE_TESTOPS_PROJECT: ${{ vars.QASE_TESTOPS_PROJECT }}
  QASE_TESTOPS_RUN_COMPLETE: true

jobs:

  run-tests:
    runs-on: ubuntu-latest
    env:
      QASE_MODE: testops
      QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
      QASE_TESTOPS_PROJECT: ${{ vars.QASE_TESTOPS_PROJECT }}
      QASE_TESTOPS_PLAN_ID: ${{ vars.QASE_TESTOPS_PLAN_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies including Qase plugin
        run: |
          pip install -r requirements.txt
          pip install qase-pytest
          pip install pytest-xdist
          pip install pytest-rerunfailures
          playwright install-deps
          playwright install webkit

      - name: Run Pytest tests with xdist workers and browser chromium
        run: |
          pytest -n 2 --browser chromium

  complete-test-run:
    needs: run-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Complete the Qase test run
        uses: qase-tms/gh-actions/run-complete@v1
        with:
          token: ${{ secrets.QASE_API_TOKEN }}
          project: ${{ vars.QASE_TESTOPS_PROJECT }}
          id: ${{ needs.create-test-run.outputs.run-id }}
